apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: amalkh/udacity-restapi-user
        name: backend-user 
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"      
        env:
        - name: URL
          value: http://localhost:8100
        - name: JWT_SECRET
          value: amal
        - name: POSTGRESS_DB
          value: POSTGRESSUSERNAME
        - name: POSTGRESS_HOST
          value: POSTGRESSUSERNAME.c5cdxrkllyu5.eu-west-3.rds.amazonaws.com
        - name: POSTGRESS_PASSWORD
          value: POSTGRESSPASSWORD
        - name: POSTGRESS_USERNAME
          value: POSTGRESSUSERNAME
      restartPolicy: Always